import './globals.css'
import {Inter} from 'next/font/google'
import {Providers} from "@/redux/provider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="fr">
        <body>
        <Providers>{children}</Providers>
        </body>
        </html>
    );
}