import './globals.css'
import {Providers} from "@/redux/Providers";
import {Layout} from "@/redux/Layout";

export const metadata = {
    title: 'V3 Bordeaux',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="fr">
        <body>
        <Providers>
            <Layout>
                {children}
            </Layout>
        </Providers>
        </body>
        </html>
    );
}