import './globals.css'
import { UXProvider } from '@/components/ux.Provider'
import { Providers } from '@/redux/Providers'

export const metadata = {
  title: 'V3 Bordeaux',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <UXProvider>
          <Providers>{children}</Providers>
        </UXProvider>
      </body>
    </html>
  )
}
