import './globals.css'
import { Providers } from '@/redux/Providers'
import { Lexend_Deca, Righteous } from 'next/font/google';

export const metadata = {
  title: 'V3 Bordeaux',
  description: 'Generated by create next app'
}

const lexendDeca = Lexend_Deca({ 
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend-deca',
});

const righteous = Righteous({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-righteous',
})

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${lexendDeca.variable} ${righteous.variable} font-sans bg-background-3 text-text-1`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
